### ISSUE TITLE
About Us Text touching navbar

### ISSUE THREAD

**Issue by toasty-bit** [pranjaljain0/portfolio-react#16]
First off nice website! Just notice that the text is touching the navbar so it could use a bit of margin-top instead of auto. 

![image](https://user-images.githubusercontent.com/63557350/95126413-13f16d00-071c-11eb-902a-008878f22055.png)

@pranjaljain0 , do tell me if this works for you and I can make a pull request

**Comment by pranjaljain0** [comment]
Sure thing @toasty-bit work on it.

**Comment by toasty-bit** [comment]
Hey @pranjaljain0 it appears it been fix already it just seems the actual website hasn't been update yet
