### ISSUE TITLE
Contact Modal is not responsive. 

### ISSUE THREAD

**Issue by Chensokheng** [pranjaljain0/portfolio-react#17]
I have notice that the contact Modal is not responsive.  When I inspected on some devices. I can not see the submit button and when I rotated the form is out of the container.

@pranjaljain0 Can I make a pull request for this issue? 

<img width="360" alt="Screen Shot 2020-10-06 at 10 11 52 AM" src="https://user-images.githubusercontent.com/52232579/95154681-95004100-07bc-11eb-8547-bbb38369c8a4.png">

![notresponsive](https://user-images.githubusercontent.com/52232579/95154752-c1b45880-07bc-11eb-8fed-1167c26acafd.jpg)

**Comment by pranjaljain0** [comment]
Sure thing @Chensokheng
