### ISSUE TITLE
Improve portfolio modal

### ISSUE THREAD

**Issue by pranjaljain0** [pranjaljain0/portfolio-react#4]
Improve portfolio modal with random data

**Comment by pranjanpr** [comment]
@pranjaljain0 please tell me more about it.

**Comment by pranjaljain0** [comment]
<img width="1440" alt="Screenshot 2020-10-01 at 10 34 46 PM" src="https://user-images.githubusercontent.com/53955200/94840621-5114e100-0436-11eb-9878-48d4e2efbc99.png">

@pranjanpr This is the current page 
There are two more elements which are to be added which are mini description and project language

**Comment by pranjanpr** [comment]
Ok so the task is to add two more card like objects in the modal. Am I right @pranjaljain0  ?

**Comment by pranjaljain0** [comment]
The task is to add one more line which will be the project description and add one more chip which will represent the programming language of the project. @pranjanpr

**Comment by pranjanpr** [comment]
Ok so the chips to be added for all the cards on the modal. @pranjaljain0

**Comment by pranjaljain0** [comment]
Yes now you're getting it. @pranjanpr

**Comment by pranjanpr** [comment]
Please assign it to me . @pranjaljain0

**Comment by pranjaljain0** [comment]
Sure @pranjanpr 👍

**Comment by pranjanpr** [comment]
Also please tell if the programming language is there in the data.

**Comment by pranjaljain0** [comment]
The data of all the projects are in JSON format and the project is react js project.

**Comment by pranjanpr** [comment]
@pranjaljain0  I am not able to find the JSON file. Where is it ?

**Comment by pranjaljain0** [comment]
@pranjanpr 
https://github.com/pranjaljain0/Portfolio-React/blob/b99cb8639e4d0789de5ed67fbaeb77e293e04b74/src/components/Home.js#L10

**Comment by pranjanpr** [comment]
See there is no mention of the programming language of a particular project. So should I add some dummy data of language in the JSON for each project ?

**Comment by pranjaljain0** [comment]
Sure @pranjanpr that works

**Comment by pranjanpr** [comment]
![Pranjal Jain - Google Chrome 02-10-2020 00_04_14](https://user-images.githubusercontent.com/57591230/94849574-4280f680-0443-11eb-9ff9-054fee7cc4a4.png)
@pranjaljain0  Please take a look if it looks good.

**Comment by pranjaljain0** [comment]
yes looks good @pranjanpr Excellent work with the chips!

**Comment by pranjanpr** [comment]
Ok so can I upload the pull request?

**Comment by pranjaljain0** [comment]
@pranjanpr sure

**Comment by pranjaljain0** [comment]
LGTM
