### ISSUE TITLE
[ Feature ] You can use Accordion in the Work Experience section so that people can describe their what they did in the job

### ISSUE THREAD

**Issue by AnirudhPanda** [pranjaljain0/portfolio-react#48]

**Comment by pranjaljain0** [comment]
Good suggestion
Will implement it on the website

**Comment by pranjaljain0** [comment]
<img width="810" alt="Screenshot 2021-07-11 at 1 49 19 PM" src="https://user-images.githubusercontent.com/53955200/125187767-cc6db380-e24e-11eb-8ea4-b8f4e45efaba.png">

**Comment by AnirudhPanda** [comment]
Looks Neat!!

**Comment by pranjaljain0** [comment]
Will close this issue
Do create other issues if you have other suggestions.
