### ISSUE TITLE
Improve Contact Us modal

### ISSUE THREAD

**Issue by pranjaljain0** [pranjaljain0/portfolio-react#5]
Improve contact us modal with proper working form.

**Comment by fernandoamz** [comment]
May I work on this?

**Comment by pranjaljain0** [comment]
Sure @fernandoamz go for it!

**Comment by fernandoamz** [comment]
@pranjaljain0, I have added changes on this pull request https://github.com/pranjaljain0/Portfolio-React/pull/6

**Comment by Aashishkushwaha** [comment]
Hi @pranjaljain0 , I want to take this up, can you assign this to me?

**Comment by pranjaljain0** [comment]
@Aashishkushwaha sure 😀

**Comment by Aashishkushwaha** [comment]
Hi @pranjaljain0 , Can you add Hacktoberfest topic to this repo?

**Comment by pranjaljain0** [comment]
@Aashishkushwaha Done that 💯 
Go for it...
