### ISSUE TITLE
Add a project description route

### ISSUE THREAD

**Issue by pranjaljain0** [pranjaljain0/portfolio-react#9]
Add a project description route which will display all the information of the selected project.

**Comment by pranjaljain0** [comment]
<img width="1440" alt="Screenshot 2020-10-04 at 5 09 39 AM" src="https://user-images.githubusercontent.com/53955200/95003739-d8fa1700-05ff-11eb-9f39-daee2d5dc024.png">
Clicking on projects will take the user to the specific page with a unique project ID.

**Comment by AlcidesA** [comment]
I can take this one! :)
